const state={view:'overview',status:null,conversations:[],conversation:null,logs:null,logType:'runtime'};
const titles={overview:['Обзор','Состояние персонального ассистента'],chat:['Диалоги','Общая история веб-чата'],max:['MAX','Управление транспортом и исходящими сообщениями'],keys:['API-ключи','Безопасное управление провайдерами'],settings:['Настройки AI','Модель, лимиты и инструкция'],stats:['Статистика','Запросы, токены и задержка'],logs:['Журнал','Безопасные события и аудит']};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escPath=value=>encodeURIComponent(value);
function notice(text,error=false){const n=$('#notice');n.textContent=text;n.className=`notice${error?' error':''}`;setTimeout(()=>n.classList.add('hidden'),4200)}
async function api(path,options={}){const mutation=options.method&&options.method!=='GET';options.headers={...(options.headers||{})};if(mutation)options.headers['X-Requested-With']='max-ai-dashboard';if(options.body&&typeof options.body!=='string'){options.headers['Content-Type']='application/json';options.body=JSON.stringify(options.body)}const r=await fetch(path,options);const type=r.headers.get('content-type')||'';const data=type.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(data.error||data||`HTTP ${r.status}`);return data}
function fmtTime(ts){return ts?new Date(ts*1000).toLocaleString('ru-RU'):'—'}
function fmtDuration(value){if(!value)return '0 мин';const h=Math.floor(value/3600),m=Math.floor(value%3600/60);return h?`${h} ч ${m} мин`:`${m} мин`}
function setView(view){state.view=view;$$('.view').forEach(x=>x.classList.remove('active'));$(`#view-${view}`).classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#page-title').textContent=titles[view][0];$('#page-subtitle').textContent=titles[view][1];if(view==='chat')loadConversations();if(view==='keys')loadKeys();if(view==='settings')loadSettings();if(view==='stats')loadStats();if(view==='logs')loadLogs()}
async function loadStatus(){try{const s=await api('/api/status');state.status=s;$('#global-state').textContent=s.running?'Работает':'Остановлен';$('#global-state').className=`badge ${s.running?'good':'bad'}`;$('#metric-max').textContent=s.max.connected?'Подключён':(s.max.phase||'Не подключён');$('#metric-max-detail').textContent=s.max.updated_at?fmtTime(s.max.updated_at):'Нет актуального события';$('#metric-runtime').textContent=s.running?'Активен':'Остановлен';$('#metric-uptime').textContent=fmtDuration(s.uptime_seconds);$('#metric-provider').textContent=s.provider;$('#metric-model').textContent=s.model;const q=s.queue;$('#metric-queue').textContent=(q.processing||0)+(q.response_ready||0);$('#metric-errors').textContent=`Ошибок: ${q.failed||0}`;$('#owner-state').textContent=s.owner_paired?'Привязан':'Не привязан';$('#last-error').textContent=s.last_error||'Нет';$('#qr-phase').textContent=`Состояние: ${s.max.phase||'unknown'}`;const img=$('#qr-image');if(['waiting_confirmation','confirmed'].includes(s.max.phase)){img.src=`/api/max/qr?t=${Date.now()}`;img.classList.remove('hidden')}else img.classList.add('hidden');const claim=$('#claim-box');if(s.max.claim_command&&!s.owner_paired){$('#claim-command').textContent=s.max.claim_command;claim.classList.remove('hidden')}else claim.classList.add('hidden');renderAuditMini(s.audit_latest)}catch(e){notice(e.message,true)}}
function renderAuditMini(items){const root=$('#audit-mini');root.textContent='';if(!items.length){root.textContent='Действий пока нет';return}items.forEach(x=>{const d=document.createElement('div');d.className='timeline-item';const strong=document.createElement('strong');strong.textContent=x.action;const small=document.createElement('small');small.textContent=`${fmtTime(x.created_at)} ${x.details||''}`;d.append(strong,small);root.append(d)})}
async function runtime(action){try{await api(`/api/runtime/${action}`,{method:'POST'});notice(`Команда «${action}» выполнена`);await loadStatus()}catch(e){notice(e.message,true)}}
async function loadKeys(){try{const keys=await api('/api/keys'),root=$('#key-cards');root.textContent='';for(const provider of ['openrouter','openai']){const card=document.createElement('article');card.className='panel';const title=document.createElement('h2');title.textContent=provider==='openrouter'?'OpenRouter':'OpenAI';const current=document.createElement('div');current.className=`key-state ${keys[provider].configured?'configured':''}`;current.textContent=keys[provider].configured?`Настроен: ${keys[provider].masked}`:'Ключ не добавлен';const form=document.createElement('form');form.className='stack';const input=document.createElement('input');input.type='password';input.autocomplete='off';input.placeholder='Новый API-ключ';const row=document.createElement('div');row.className='button-row';const save=document.createElement('button');save.className='button primary';save.textContent='Сохранить';const test=document.createElement('button');test.type='button';test.className='button';test.textContent='Проверить';const del=document.createElement('button');del.type='button';del.className='button danger-outline';del.textContent='Удалить';row.append(save,test,del);form.append(input,row);form.addEventListener('submit',async e=>{e.preventDefault();try{await api(`/api/keys/${provider}`,{method:'PUT',body:{key:input.value}});input.value='';notice('Ключ сохранён');loadKeys();loadStatus()}catch(err){notice(err.message,true)}});test.onclick=async()=>{try{const r=await api(`/api/keys/${provider}/test`,{method:'POST'});notice(r.ok?`Подключение успешно (HTTP ${r.status})`:`Ключ отклонён (HTTP ${r.status})`,!r.ok)}catch(err){notice(err.message,true)}};del.onclick=async()=>{if(!confirm(`Удалить ключ ${provider}? Активный AI будет остановлен.`))return;try{await api(`/api/keys/${provider}`,{method:'DELETE'});notice('Ключ удалён');loadKeys();loadStatus()}catch(err){notice(err.message,true)}};card.append(title,current,form);root.append(card)}}catch(e){notice(e.message,true)}}
async function loadSettings(){try{const data=await api('/api/settings'),form=$('#settings-form');for(const [k,v] of Object.entries(data.settings)){const el=form.elements.namedItem(k);if(el)el.value=v} }catch(e){notice(e.message,true)}}
async function saveSettings(e){e.preventDefault();const values={};new FormData(e.currentTarget).forEach((v,k)=>values[k]=v);for(const k of ['llm_timeout','llm_daily_limit','llm_daily_token_limit','llm_max_output_tokens','llm_max_retries','llm_history_messages','llm_max_input_chars'])values[k]=Number(values[k]);try{const r=await api('/api/settings',{method:'PUT',body:values});notice(r.restarted?'Настройки сохранены, AI перезапущен':'Настройки сохранены');loadStatus()}catch(err){notice(err.message,true)}}
async function loadConversations(){try{const data=await api('/api/conversations');state.conversations=data.items;const root=$('#conversation-list');root.textContent='';data.items.forEach(c=>{const item=document.createElement('div');item.className=`conversation-item ${state.conversation===c.id?'active':''}`;item.textContent=c.title;const small=document.createElement('small');small.textContent=fmtTime(c.updated_at);item.append(small);item.onclick=()=>openConversation(c.id);root.append(item)});if(!state.conversation&&data.items.length)openConversation(data.items[0].id)}catch(e){notice(e.message,true)}}
async function newConversation(){try{const c=await api('/api/conversations',{method:'POST',body:{}});state.conversation=c.id;await loadConversations();await openConversation(c.id)}catch(e){notice(e.message,true)}}
async function openConversation(id){try{state.conversation=id;const data=await api(`/api/conversations/${escPath(id)}/messages`);$('#chat-title').textContent=data.conversation.title;const root=$('#messages');root.textContent='';if(!data.messages.length){const e=document.createElement('div');e.className='empty-state';e.textContent='Сообщений пока нет';root.append(e)}data.messages.forEach(renderMessage);const input=$('#chat-input');input.disabled=false;$('#chat-form button').disabled=false;root.scrollTop=root.scrollHeight;$$('.conversation-item').forEach((el,i)=>el.classList.toggle('active',state.conversations[i]?.id===id))}catch(e){notice(e.message,true)}}
function renderMessage(m){const d=document.createElement('div');d.className=`message ${m.role}`;const text=document.createElement('div');text.textContent=m.content;const small=document.createElement('small');small.textContent=fmtTime(m.created_at);d.append(text,small);$('#messages').append(d)}
async function sendChat(e){e.preventDefault();if(!state.conversation)return;const input=$('#chat-input'),text=input.value.trim(),button=e.currentTarget.querySelector('button');if(!text)return;input.value='';input.disabled=true;button.disabled=true;renderMessage({role:'user',content:text,created_at:Date.now()/1000});try{await api(`/api/conversations/${escPath(state.conversation)}/messages`,{method:'POST',body:{text}});await openConversation(state.conversation);await loadConversations();loadStats()}catch(err){notice(err.message,true)}finally{input.disabled=false;button.disabled=false;input.focus()}}
async function clearChat(){if(!state.conversation||!confirm('Начать новый контекст в этом диалоге?'))return;try{await api(`/api/conversations/${escPath(state.conversation)}/clear`,{method:'POST'});await openConversation(state.conversation);loadConversations()}catch(e){notice(e.message,true)}}
async function deleteChat(){if(!state.conversation||!confirm('Удалить диалог и его сообщения без возможности восстановления?'))return;try{await api(`/api/conversations/${escPath(state.conversation)}`,{method:'DELETE'});state.conversation=null;$('#messages').textContent='';$('#chat-input').disabled=true;$('#chat-form button').disabled=true;loadConversations()}catch(e){notice(e.message,true)}}
function exportChat(){if(state.conversation)location.href=`/api/conversations/${escPath(state.conversation)}/export`}
async function sendMax(e){e.preventDefault();const input=$('#max-input'),text=input.value.trim();if(!text)return;try{await api('/api/max/send',{method:'POST',body:{text}});input.value='';notice('Сообщение отправлено в MAX')}catch(err){notice(err.message,true)}}
async function provide2fa(e){e.preventDefault();const input=$('#twofa-input');try{await api('/api/max/2fa',{method:'POST',body:{password:input.value}});input.value='';notice('2FA передан локальному клиенту')}catch(err){notice(err.message,true)}}
async function revokeMax(){if(!confirm('Выйти из MAX и удалить локальную сессию устройства? Для повторного входа потребуется новый QR.'))return;try{await api('/api/max/revoke',{method:'POST',body:{confirm:true}});notice('Локальная MAX-сессия удалена');loadStatus()}catch(e){notice(e.message,true)}}
async function loadStats(){try{const s=await api('/api/stats?days=14'),x=s.summary;$('#stat-total').textContent=x.total||0;$('#stat-success').textContent=`${x.success||0} успешных, ${x.errors||0} ошибок`;$('#stat-tokens').textContent=Number(x.input_tokens+x.output_tokens).toLocaleString('ru-RU');$('#stat-token-split').textContent=`вход ${x.input_tokens} / выход ${x.output_tokens}`;$('#stat-latency').textContent=`${(x.avg_latency_ms/1000).toFixed(1)} с`;$('#stat-cost').textContent=`$${Number(x.cost||0).toFixed(4)}`;const chart=$('#daily-chart');chart.textContent='';const max=Math.max(1,...s.daily.map(d=>d.requests));s.daily.forEach(d=>{const c=document.createElement('div');c.className='bar-column';const b=document.createElement('div');b.className='bar';b.style.setProperty('--h',`${Math.max(3,d.requests/max*170)}px`);b.title=`${d.requests} запросов, ${d.tokens} токенов`;const l=document.createElement('span');l.textContent=d.day.slice(5);c.append(b,l);chart.append(c)});const models=$('#model-stats');models.textContent='';s.models.forEach(m=>{const r=document.createElement('div');r.className='table-row';[`${m.provider} · ${m.model}`,`${m.requests} запр.`,`${m.tokens} ток.`].forEach(v=>{const e=document.createElement('span');e.textContent=v;r.append(e)});models.append(r)})}catch(e){notice(e.message,true)}}
async function loadLogs(){try{state.logs=await api('/api/logs');renderLogs()}catch(e){notice(e.message,true)}}
function renderLogs(){const root=$('#log-list');root.textContent='';const items=state.logs?.[state.logType]||[];items.forEach(x=>{const r=document.createElement('div');r.className='log-row';const t=document.createElement('span');t.className='muted';t.textContent=fmtTime(x.created_at);const level=document.createElement('span');level.textContent=x.level||x.action;const msg=document.createElement('span');msg.textContent=x.message||x.details||'';r.append(t,level,msg);root.append(r)});if(!items.length)root.textContent='Событий пока нет'}
function bind(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);const run=e.target.closest('[data-runtime]');if(run)runtime(run.dataset.runtime)});$('#refresh').onclick=()=>{loadStatus();if(state.view==='stats')loadStats();if(state.view==='logs')loadLogs()};$('#theme-toggle').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('theme',document.documentElement.classList.contains('light')?'light':'dark')};$('#settings-form').onsubmit=saveSettings;$('#settings-form [name="llm_provider"]').onchange=e=>{const defaults={openrouter:{url:'https://openrouter.ai/api/v1',model:'openrouter/free'},openai:{url:'https://api.openai.com/v1',model:'gpt-5.6-luna'}}[e.target.value];$('#settings-form [name="llm_base_url"]').value=defaults.url;$('#settings-form [name="llm_model"]').value=defaults.model};$('#new-conversation').onclick=newConversation;$('#chat-form').onsubmit=sendChat;$('#clear-chat').onclick=clearChat;$('#delete-chat').onclick=deleteChat;$('#export-chat').onclick=exportChat;$('#max-form').onsubmit=sendMax;$('#twofa-form').onsubmit=provide2fa;$('#copy-claim').onclick=()=>navigator.clipboard.writeText($('#claim-command').textContent).then(()=>notice('Claim-команда скопирована')).catch(()=>notice('Не удалось скопировать команду',true));$('#revoke-max').onclick=revokeMax;$$('[data-log]').forEach(b=>b.onclick=()=>{$$('[data-log]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.logType=b.dataset.log;renderLogs()});if(localStorage.getItem('theme')==='light')document.documentElement.classList.add('light')}
bind();loadStatus();setInterval(loadStatus,10000);
